baseurl = "https://blog.sivaratnakar.com"
metaDataFormat = "yaml"
title = "The Curious Explorer"
theme = "blist"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = false
[languages]
  [languages.en]
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "The Curious Explorer"
      introSubtitle = "Welcome!!  Explore the world with me."
      introPhoto = "/me-on-car.webp"
      logo = "/logo.svg"
      permalink = "https://sivaratnakar.com/"

    [[languages.en.menu.main]]
        name = "Bio Blog"
        url = "/blog/"
        weight = 1
    [[languages.en.menu.main]]
        name = "Life"
        url = "/life/"
        weight = 2

[module]
[[module.mounts]]
    source = 'static/img'
    target = 'assets/img'

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

  # Custom copyright - optional
  copyright = "Copyright © 2023 - Sivaratnakar · All rights reserved"
  favicon = "/logo.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = true

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = false

# Comments system
[params.comments]
  # Supports disqus, giscus and utterances
  # Check hugo docs for setting up disqus
  system = "giscus"

  # Options for giscus, exclude hyphens
  repo = ""
  repoid = ""
  category = ""
  categoryid = ""
  mapping = ""
  strict = ""
  reactionsenabled = ""
  emitmetadata = ""
  inputposition = ""
  theme = ""

  # Options for utterances, exclude hyphens
  # repo = ""
  # issueterm = ""
  # theme = ""

[params.homepage.social]
  # Global params common for both languages
  title = "Follow me"
  description = "I like to simplify Biology."

  [[params.homepage.social.icons]]
    website = "twitter"
    url = "https://twitter.com/SivaRatnakar"
  [[params.homepage.social.icons]]
    website = "linkedin"
    url = "https://linkedin.com/in/siva-ratnakar"
  [[params.homepage.social.icons]]
    website = "telegram"
    url = "https://t.me/siva_ratnakar"
  [[params.homepage.social.icons]]
    website = "github"
    url = "https://github.com/siva-ratnakar"
  [[params.homepage.social.icons]]
    website = "googlescholar"
    url = "https://scholar.google.com/citations?user=CTIJ3LQAAAAJ&hl=en"
  [[params.homepage.social.icons]]
    website = "instagram"
    url = "https://instagram.com/siva_ratnakar"
  [[params.homepage.social.icons]]
    website = "facebook"
    url = "https://facebook.com/sivaratnakar.immadi"
  
[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
